INSERT INTO TOOL_TYPES VALUES (1, 'Ladder', 1.99, TRUE, TRUE, FALSE);
INSERT INTO TOOL_TYPES VALUES (2, 'Chainsaw', 1.49, TRUE, FALSE, TRUE);
INSERT INTO TOOL_TYPES VALUES (3, 'Jackhammer', 2.99, TRUE, FALSE, FALSE);

INSERT INTO TOOLS VALUES (1, 'CHNS', 2, 'Stihl');
INSERT INTO TOOLS VALUES (2, 'LADW', 1, 'Werner');
INSERT INTO TOOLS VALUES (3, 'JAKD', 3, 'DeWalt');
INSERT INTO TOOLS VALUES (4, 'JAKR', 3, 'Ridgid');


